test_case_generator_task:
  description: >
    Create test case scenarios for {{topic}} integration testing.`
  expected_output: >
    A list with 10 test cases for {topic} integration testing.
  agent: test_case_generator

test_case_writer_task:
  description: >
    Write a test case for the following scenario:
    ### SCENARIO:
    {{scenario}}
    format the test case in the following format:
    ### TEST CASE:
    {{test_case}}
    ## preconditions:
    {{preconditions}}
    ## steps:
    {{steps}}
    ## expected result:
    {{expected_result}}
    
  expected_output: >
    A test case formatted as markdown without '```'
  agent: test_case_writer
