table_description_task:
  description: >
    Provide the comprehensive overview for the data 
    in table {table}, so that it's easy to understand the structure 
    of the data. This task is crucial to put together the documentation 
    for our database
  expected_output: >
    The comprehensive overview of {table} in the md format. 
    Include 2 sections: columns (list of columns with their types) 
    and examples (the first 30 rows from table).
table_documentation_task:
  description: >
    Using provided information about the table, 
    put together the detailed documentation for this table so that 
    people can use it in practice
  expected_output: >
    Well-written detailed documentation describing 
    the data scheme for the table {table} in markdown format, 
    that gives the table overview in 1-2 sentences then then 
    describes each columm. Structure the columns description 
    as a markdown table with column name, type and description.

